// Abstract Syntax Tree - Tree representation of diagram objects
// This is the intermediate representation between parsing and rendering

import type { Token } from '../parser/lexer';

export type DiagramType = 
  | 'uml2.5-component'
  | 'uml2.5-class'
  | 'uml2.5-sequence'
  | 'uml2.5-activity';

export interface ASTPort {
  id: string;
  label?: string;
  side: 'left' | 'right' | 'top' | 'bottom';
  offset?: number;
  connectorRef?: string; // Reference to a named connector
}

export interface ASTNode {
  id: string;
  label: string;
  x?: number; // Optional: may be set by layout or user
  y?: number; // Optional: may be set by layout or user
  width?: number; // Computed by layout
  height?: number; // Computed by layout
  children: ASTNode[]; // Tree structure - children nested here
  ports: ASTPort[];
}

export interface ASTConnector {
  id: string;
  name?: string; // Optional name for the connector (e.g., "Connection1")
  sourceNodeId: string;
  targetNodeId: string;
  sourcePortId?: string;
  targetPortId?: string;
  label?: string;
  isDelegate?: boolean;
  isAutoGenerated?: boolean; // True for automatically generated delegates
  stereotype?: string;
  edgeType?: string; // KEEP element type for now? or rename to connectorType?
}

export interface DiagramAST {
  type: DiagramType;
  rootNodes: ASTNode[]; // Top-level nodes only
  connectors: ASTConnector[]; // All edges (flat list)
  tokens?: any[];
}
